title = "Files to copy"

max_threads = 4

#rate in MB (0 - unrestricted)
max_rate = 30

#distination absolute path
dist = "q:\\"

#files to be copied
files = ["first.dat", "second.dat", "third.dat", "fourth.dat"]